site_name: Luke
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
  font:
    code: Source Code Pro
nav:
  - Python:
    - python/concept.md
    - python/library.md
    - python/snippets.md
    - python/requests.md
    - python/flask.md
    - python/celery.md
    - python/click.md
  - Notes:
    - notes/commands.md
    - notes/mongodb.md
    - notes/python.md
    - notes/sql.md
    - notes/java.md
    - notes/tools.md
  - Blog:
    - blog/index.md
plugins:
  - blog
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css