site_name: Luke Clark
theme:
  name: material
  palette:
    scheme: slate
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
nav:
  - Python:
    - core.md
    - library.md
    - snippets.md
    - requests.md
    - flask.md
    - celery.md
    - click.md
  - Blog:
    - blog/index.md
plugins:
  - blog
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
